In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(42)

rows = 5000

In [23]:
df = pd.DataFrame({

    'DV01': np.random.randint(
        50000,
        250000,
        rows
    ),

    'Vega': np.random.randint(
        10000,
        150000,
        rows
    ),

    'Gamma': np.random.randint(
        1000,
        30000,
        rows
    ),

    'MarketMove': np.random.uniform(
        0.1,
        1.5,
        rows
    ),

    'VaR': np.random.randint(
        100000,
        600000,
        rows
    ),

    'ResidualPnL': np.random.randint(
        1000,
        100000,
        rows
    ),

    'TradeCount': np.random.randint(
        100,
        1000,
        rows
    )

})
df

        DV01    Vega  Gamma  MarketMove     VaR  ResidualPnL  TradeCount
0     209015   75725   2581    0.313346  277401        99994         315
1     244330  121912  14662    1.014219  298102        14067         882
2      96368  124632  19813    1.439022  286696        75523         501
3     207934  123799   1837    0.964782  178260        43989         152
4     154226   57149   2576    1.458294  326062        87380         666
...      ...     ...    ...         ...     ...          ...         ...
4995  224834  148097  21294    0.240971  175996        63265         277
4996  112566  134109  16522    1.018008  553627        14209         145
4997   78799   14031  29634    0.735675  232284        12870         913
4998  221547   13544  24242    0.160743  591241        25934         111
4999  161820   39117   7390    1.091515  260696        38047         556

[5000 rows x 7 columns]

In [25]:
#Business Logic
df['ReconBreak'] = np.where(

(
(df['ResidualPnL'] > 50000)
&
(df['MarketMove'] > 0.8)
)

|
(
df['TradeCount'] > 700
),

1,

0
)

In [31]:
df.head()

,DV01,Vega,Gamma,MarketMove,VaR,ResidualPnL,TradeCount,ReconBreak
0,209015,75725,2581,0.313346,277401,99994,315,0
1,244330,121912,14662,1.014219,298102,14067,882,1
2,96368,124632,19813,1.439022,286696,75523,501,1
3,207934,123799,1837,0.964782,178260,43989,152,0
4,154226,57149,2576,1.458294,326062,87380,666,1

In [33]:
#df.to_csv('C:\\Pradeep\\udemy Final\\PNL_Analysis\\data\\pnl_risk_data.csv',index=False)

df.to_csv( r'C:\Pradeep\udemy Final\PNL_Analysis\data\pnl_risk_data.csv', index=False )

#df = pd.read_csv(
#    r'C:\Pradeep\udemy Final\PNL_Analysis\data\pnl_risk_data.csv'